name: Python package

on: [push]

env:
  PACKAGE_DIR_NAME: sphinx_autopyproject
  PACKAGE_NAME: sphinx-autopyproject

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -m pip install --upgrade pip wheel build twine
      - name: Building packages
        run: python -m build
      - name: Checking packages
        run: python -m twine check dist/*
      - uses: actions/upload-artifact@v3
        if: ${{ !env.ACT }}
        with:
          name: ${{ env.PACKAGE_NAME }}
          path: dist/*
      - name: Publish distribution to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@v1.5.1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
