name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: python -m pip install --upgrade pip wheel build twine
      - name: Building packages
        run: python -m build
      - name: Checking packages
        run: python -m twine check dist/*
      - name: Get repository name
        run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
      - uses: actions/upload-artifact@v3
        if: ${{ !env.ACT }}
        with:
          name: ${{ env.REPOSITORY_NAME }}
          path: dist/*
      - name: Publish distribution to PyPI
        if: ${{ !env.ACT && startsWith(github.ref, 'refs/tags') }}
        uses: pypa/gh-action-pypi-publish@v1.5.1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
